### ISSUE TITLE
Breaks with a TSConfig that "extends" from an external config file

### ISSUE THREAD

**Issue by alexlafroscia** [antongolub/tsc-esm-fix#174]
I tried running this tool on a package of mine that has a `tsconfig.json` that extends from a shared, external config file

```json
// Config file at `/Users/me/Code/project/tsconfig.json`
{
  "extends": "@company/configs/tsconfig.json"
}
```

The way that the `extends` field is handled assumes that you're extending form a local file that can be resolved relative to the one being parsed

https://github.com/antongolub/tsc-esm-fix/blob/master/src/main/ts/util.ts#L31

This is resulting in an exception being raised when trying to run the tool, as it tries and fails to append the external config file's identifier to the directory of the project's config file; with the example config given above at the specified path, the resulting exception would look like

```
Error: ENOENT: no such file or directory, open '/Users/me/Code/project/@company/configs/tsconfig.json'
```

**Comment by antongolub** [comment]
@alexlafroscia

Oh, I forgot to land [@topoconfig/extends](https://github.com/antongolub/misc/tree/master/packages/topoconfig/extends) here. It's ironic. Thanks for highlighting the issue.

**Comment by MirKml** [comment]
hello @antongolub 
this fix in 3.1.1  now produces this fatal error for me
```
SyntaxError: Expected double-quoted property name in JSON at position 111
    at JSON.parse (<anonymous>)
    at parse (node_modules/@topoconfig/extends/target/esm/index.mjs:52:36)
    at node_modules/@topoconfig/extends/target/esm/index.mjs:96:40
    at pipe (node_modules/@topoconfig/extends/target/esm/index.mjs:23:68)
    at processResource (file:node_modules/@topoconfig/extends/target/esm/index.mjs:91:34)
    at loadResource (node_modules/@topoconfig/extends/target/esm/index.mjs:82:19)
    at populateSync (node_modules/@topoconfig/extends/target/esm/index.mjs:224:19)
    at resolveTsConfig (node_modules/tsc-esm-fix/target/esm/util.mjs:12:42)
    at node_modules/tsc-esm-fix/target/esm/finder.mjs:15:26
    at Array.reduce (<anonymous>)
```

previous 3.1.0 is without any fatal error

**Comment by antongolub** [comment]
Mea culpa. Missing json5 parser.
